/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface PresetPrompt {
  color: string;
  text: string;
}

export interface Preset {
  name: string;
  description: string;
  prompts: PresetPrompt[];
}

export const REGIONAL_PRESETS: Record<string, Preset> = {
  'southern-trap': {
    name: 'Southern Trap',
    description: 'Hard-hitting 808s, rapid hi-hats, dark synths',
    prompts: [
      { color: '#ff0000', text: 'Booming 808 Bass' },
      { color: '#8b0000', text: 'Trap Snare Rolls' },
      { color: '#ff4500', text: 'Rapid Hi-Hat Patterns' },
      { color: '#dc143c', text: 'Dark Synth Leads' },
      { color: '#b22222', text: 'Sub Bass Drops' },
      { color: '#ff6347', text: 'Triplet Hi-Hats' },
      { color: '#cd5c5c', text: 'Heavy Kick Drums' },
      { color: '#8b4513', text: 'Atmospheric Pads' },
      { color: '#a52a2a', text: 'Arpeggio Synths' },
      { color: '#ff8c00', text: 'Chopped Vocal Samples' },
      { color: '#d2691e', text: 'Layered Claps' },
      { color: '#ff1493', text: 'Pitch-Shifted Melodies' },
      { color: '#800020', text: 'Rolling Bass Lines' },
      { color: '#b8860b', text: 'Synth Brass Hits' },
      { color: '#8b008b', text: 'Gliding Lead Synth' },
      { color: '#9932cc', text: 'Reversed Cymbal' },
    ],
  },
  'california-gfunk': {
    name: 'California G-Funk',
    description: 'Funky basslines, vibraslap, synthesizers with that West Coast vibe',
    prompts: [
      { color: '#ffd700', text: 'Funky Bass Lines' },
      { color: '#ffa500', text: 'Vibraslap Hits' },
      { color: '#ff8c00', text: 'Synth Keys' },
      { color: '#ffff00', text: 'Hydraulic Kick' },
      { color: '#daa520', text: 'Talkbox Effects' },
      { color: '#b8860b', text: 'Smooth Lead Synth' },
      { color: '#f0e68c', text: 'Laid Back Drums' },
      { color: '#ffefd5', text: 'Whistling Synth' },
      { color: '#ffe4b5', text: 'Warm Bass Pads' },
      { color: '#deb887', text: 'Moog-Style Lead' },
      { color: '#d2b48c', text: 'Rhodes Electric Piano' },
      { color: '#bc8f8f', text: 'Analog Funk Keys' },
      { color: '#cd853f', text: 'Slap Bass Groove' },
      { color: '#f4a460', text: 'Vocoder Vocals' },
      { color: '#8b7355', text: 'Retro Drum Machine' },
      { color: '#a0522d', text: 'Smooth Strings' },
    ],
  },
  'bay-area-hyphy': {
    name: 'Bay Area Hyphy',
    description: 'Energetic, uptempo beats with bouncy basslines',
    prompts: [
      { color: '#00bfff', text: 'Bouncing Bass' },
      { color: '#1e90ff', text: 'Hyper Drums' },
      { color: '#4169e1', text: 'Energetic Synth' },
      { color: '#6495ed', text: 'Rapid Fire Claps' },
      { color: '#00ced1', text: 'Upbeat Keys' },
      { color: '#40e0d0', text: 'Staccato Horns' },
      { color: '#48d1cc', text: 'Percussive Hits' },
      { color: '#afeeee', text: 'Fast Hi-Hats' },
      { color: '#7fffd4', text: 'Bright Synth Stabs' },
      { color: '#66cdaa', text: 'Thizz Whistle' },
      { color: '#5f9ea0', text: 'Quick Snare Rolls' },
      { color: '#4682b4', text: 'Party Vocal Samples' },
      { color: '#b0c4de', text: 'Choppy Chords' },
      { color: '#add8e6', text: 'Uptempo Bass Kicks' },
      { color: '#87ceeb', text: 'Electric Lead' },
      { color: '#87cefa', text: 'Energized Pads' },
    ],
  },
  'texas-trunk': {
    name: 'Texas Pop Trunk',
    description: 'Deep bass, chopped and screwed elements, modern and classic Houston sound',
    prompts: [
      { color: '#800080', text: 'Deep Sub Bass' },
      { color: '#9370db', text: 'Chopped Vocals' },
      { color: '#8a2be2', text: 'Slowed Tempo' },
      { color: '#9400d3', text: 'Heavy 808 Kick' },
      { color: '#9932cc', text: 'Screwed Synth' },
      { color: '#ba55d3', text: 'Trunk-Rattling Bass' },
      { color: '#da70d6', text: 'Dragging Hi-Hats' },
      { color: '#ee82ee', text: 'Pitched Down Keys' },
      { color: '#dda0dd', text: 'Reverb Snares' },
      { color: '#d8bfd8', text: 'Lo-Fi Texture' },
      { color: '#ff00ff', text: 'Bass Guitar Plucks' },
      { color: '#ff1493', text: 'Slowed Strings' },
      { color: '#c71585', text: 'Deep Vocal Chops' },
      { color: '#db7093', text: 'Mellow Pad' },
      { color: '#ff69b4', text: 'Slow Roll Drums' },
      { color: '#ff6eb4', text: 'Chilled Keys' },
    ],
  },
  'memphis-phonk': {
    name: 'Memphis Phonk',
    description: 'Dark horror vibes, cowbells, sprinkler hi-hats, long snare rolls',
    prompts: [
      { color: '#2f4f4f', text: 'Dark Horror Keys' },
      { color: '#191970', text: 'Memphis Cowbell' },
      { color: '#000080', text: 'Sprinkler Hi-Hats' },
      { color: '#00008b', text: 'Long Snare Rolls' },
      { color: '#483d8b', text: 'Arpeggio Synth' },
      { color: '#1c1c1c', text: 'Eerie Melody' },
      { color: '#36454f', text: 'Distorted Bass' },
      { color: '#0a0a0a', text: 'Haunting Vocal Sample' },
      { color: '#2c2c2c', text: 'Lo-Fi Drums' },
      { color: '#3c3c3c', text: 'Vinyl Crackle' },
      { color: '#4b0082', text: 'Triplet Flow' },
      { color: '#1a1a2e', text: 'Dark Ambient Pad' },
      { color: '#16213e', text: 'Horror Strings' },
      { color: '#0f3460', text: 'Deep Kick' },
      { color: '#533483', text: 'Evil Laugh Sample' },
      { color: '#1f1f1f', text: 'Reverse Cymbal' },
    ],
  },
  'florida-bass': {
    name: 'Florida Bass',
    description: 'High-energy bass music with tropical influences',
    prompts: [
      { color: '#ff6f61', text: 'Rolling Bass' },
      { color: '#ff9966', text: 'Tropical Percussion' },
      { color: '#ffb347', text: 'Energetic Kicks' },
      { color: '#ff7f50', text: 'Party Vocal Chants' },
      { color: '#ff8c69', text: 'Fast Snare Patterns' },
      { color: '#ffa07a', text: 'Bright Synth Leads' },
      { color: '#ff4500', text: 'Heavy Bass Drops' },
      { color: '#ff6347', text: 'Layered Hi-Hats' },
      { color: '#cd5c5c', text: 'Wobble Bass' },
      { color: '#f08080', text: 'Horn Stabs' },
      { color: '#fa8072', text: 'Rapid Drums' },
      { color: '#e9967a', text: 'Melodic Hooks' },
      { color: '#ffc0cb', text: 'Bouncy Bassline' },
      { color: '#ffb6c1', text: 'Club Percussion' },
      { color: '#ff69b4', text: 'Energized Pads' },
      { color: '#ff1493', text: 'Festival Synth' },
    ],
  },
  'chicago-drill': {
    name: 'Chicago Drill',
    description: 'Aggressive beats, dark atmosphere, heavy 808s',
    prompts: [
      { color: '#000000', text: 'Heavy 808 Slides' },
      { color: '#0d0d0d', text: 'Dark Piano Keys' },
      { color: '#1a1a1a', text: 'Aggressive Snares' },
      { color: '#262626', text: 'Menacing Bass' },
      { color: '#333333', text: 'Rolling Hi-Hats' },
      { color: '#404040', text: 'Drill Snare Pattern' },
      { color: '#4d4d4d', text: 'Haunting Melody' },
      { color: '#595959', text: 'Sub Bass Rumble' },
      { color: '#666666', text: 'Dark Strings' },
      { color: '#737373', text: 'Layered Kicks' },
      { color: '#808080', text: 'Ominous Pad' },
      { color: '#8b8b8b', text: 'Distorted Lead' },
      { color: '#a9a9a9', text: 'Vocal Sample Chops' },
      { color: '#696969', text: 'Hard Claps' },
      { color: '#2f4f4f', text: 'Deep Reverb' },
      { color: '#556b2f', text: 'Cinematic Tension' },
    ],
  },
  'ny-boom-bap': {
    name: 'New York Boom Bap',
    description: 'Classic hip-hop drums, jazz samples, soulful loops',
    prompts: [
      { color: '#8b4513', text: 'Punchy Kick' },
      { color: '#a0522d', text: 'Snappy Snare' },
      { color: '#cd853f', text: 'Jazz Piano Loop' },
      { color: '#deb887', text: 'Dusty Hi-Hats' },
      { color: '#f4a460', text: 'Vinyl Scratch' },
      { color: '#d2691e', text: 'Soul Vocal Sample' },
      { color: '#bc8f8f', text: 'Upright Bass' },
      { color: '#fff8dc', text: 'Mellow Keys' },
      { color: '#ffebcd', text: 'Trumpet Stabs' },
      { color: '#ffe4c4', text: 'String Section' },
      { color: '#ffdead', text: 'Acoustic Drums' },
      { color: '#navajowhite', text: 'Warm Bass Line' },
      { color: '#wheat', text: 'Saxophone Melody' },
      { color: '#burlywood', text: 'Boom Bap Beat' },
      { color: '#tan', text: 'Old School Pads' },
      { color: '#rosybrown', text: 'Vinyl Crackle' },
    ],
  },
};

export const MODERN_PRESETS: Record<string, Preset> = {
  'j-pop': {
    name: 'J-Pop',
    description: 'Upbeat, colorful, energetic pop with synthesizers',
    prompts: [
      { color: '#ff69b4', text: 'Bright Synth Lead' },
      { color: '#ff1493', text: 'Cute Vocal Chops' },
      { color: '#ff00ff', text: 'Energetic Drums' },
      { color: '#da70d6', text: 'Playful Keys' },
      { color: '#ee82ee', text: 'Upbeat Bass' },
      { color: '#dda0dd', text: 'Sparkle Effects' },
      { color: '#ffb6c1', text: 'Happy Melody' },
      { color: '#ffc0cb', text: 'Bouncy Rhythm' },
      { color: '#db7093', text: 'Synth Pop Chords' },
      { color: '#ff6eb4', text: 'Kawaii Bells' },
      { color: '#c71585', text: 'Electronic Beat' },
      { color: '#ff1493', text: 'Catchy Hooks' },
      { color: '#ff69b4', text: 'Colorful Pads' },
      { color: '#ff0099', text: 'Pop Strings' },
      { color: '#ff33cc', text: 'Cheerful Arps' },
      { color: '#cc0099', text: 'Dance Beat' },
    ],
  },
  'darkwave': {
    name: 'Darkwave',
    description: 'Dark synths, post-punk influences, moody atmosphere',
    prompts: [
      { color: '#1a1a2e', text: 'Dark Synth Pads' },
      { color: '#16213e', text: 'Gothic Bass' },
      { color: '#0f3460', text: 'Cold Wave Keys' },
      { color: '#2c3e50', text: 'Haunting Melody' },
      { color: '#34495e', text: 'Reverb Drums' },
      { color: '#1c1c1c', text: 'Moody Arpeggios' },
      { color: '#191970', text: 'Ethereal Vocals' },
      { color: '#000080', text: 'Deep Bass Line' },
      { color: '#00008b', text: 'Atmospheric Pad' },
      { color: '#483d8b', text: 'Post-Punk Guitar' },
      { color: '#4b0082', text: 'Synth Strings' },
      { color: '#2f4f4f', text: 'Dark Percussion' },
      { color: '#36454f', text: 'Ominous Chords' },
      { color: '#0a0a0a', text: 'Shadow Textures' },
      { color: '#2c2c2c', text: 'Cold Synth Lead' },
      { color: '#3c3c3c', text: 'Melancholic Keys' },
    ],
  },
  'brazilian-phonk': {
    name: 'Brazilian Phonk',
    description: 'Funk carioca meets phonk, aggressive bass and Brazilian samples',
    prompts: [
      { color: '#009c3b', text: 'Baile Funk Beat' },
      { color: '#002776', text: 'Brazilian Vocal Sample' },
      { color: '#ffdf00', text: 'Aggressive 808' },
      { color: '#228b22', text: 'Cowbell Rhythm' },
      { color: '#32cd32', text: 'Favela Bass' },
      { color: '#00ff00', text: 'Tamborzão Drums' },
      { color: '#adff2f', text: 'Funk Melody' },
      { color: '#7fff00', text: 'Heavy Kick' },
      { color: '#00fa9a', text: 'Distorted Bass' },
      { color: '#00ff7f', text: 'Rapid Hi-Hats' },
      { color: '#3cb371', text: 'Brazilian Percussion' },
      { color: '#2e8b57', text: 'Phonk Keys' },
      { color: '#8fbc8f', text: 'Brass Stabs' },
      { color: '#90ee90', text: 'Vocal Chants' },
      { color: '#98fb98', text: 'Club Bass' },
      { color: '#00ff00', text: 'Carnival Energy' },
    ],
  },
  'k-pop': {
    name: 'K-Pop',
    description: 'Polished pop production with EDM influences',
    prompts: [
      { color: '#ff6b9d', text: 'Synth Pop Lead' },
      { color: '#c44569', text: 'Vocal Harmonies' },
      { color: '#f8b500', text: 'EDM Bass Drop' },
      { color: '#feca57', text: 'Bright Synth Chords' },
      { color: '#ee5a6f', text: 'Dance Beat' },
      { color: '#ff6348', text: 'Catchy Hook' },
      { color: '#ff4757', text: 'Layered Vocals' },
      { color: '#ff7979', text: 'Pop Drums' },
      { color: '#ffb142', text: 'Energetic Keys' },
      { color: '#ffa502', text: 'Synth Plucks' },
      { color: '#ff6348', text: 'Punchy Bass' },
      { color: '#ff4757', text: 'Electronic Fills' },
      { color: '#ff6b81', text: 'Pop Strings' },
      { color: '#fd79a8', text: 'Sparkle Synth' },
      { color: '#e84393', text: 'Modern Beat' },
      { color: '#a29bfe', text: 'Bright Pads' },
    ],
  },
  'pluggnb': {
    name: 'PluggnB',
    description: 'Plugg beats meets R&B, melodic and dreamy',
    prompts: [
      { color: '#a8e6cf', text: 'Dreamy Bells' },
      { color: '#dcedc1', text: 'Soft 808 Bass' },
      { color: '#ffd3b6', text: 'Melodic Plucks' },
      { color: '#ffaaa5', text: 'Airy Vocals' },
      { color: '#ff8b94', text: 'Smooth Keys' },
      { color: '#b8b8ff', text: 'Plugg Hi-Hats' },
      { color: '#c7ceea', text: 'R&B Chords' },
      { color: '#ffdac1', text: 'Ethereal Pad' },
      { color: '#e2f0cb', text: 'Soft Snare' },
      { color: '#b5ead7', text: 'Lush Strings' },
      { color: '#c7ceea', text: 'Ambient Texture' },
      { color: '#ff9cee', text: 'Vocal Runs' },
      { color: '#b4a7d6', text: 'Chill Bass' },
      { color: '#a8e6cf', text: 'Mellow Lead' },
      { color: '#ffdab9', text: 'Gentle Drums' },
      { color: '#e6e6fa', text: 'Dreamy Arps' },
    ],
  },
  'eco-electronica': {
    name: 'Eco-Friendly Electronica',
    description: 'Nature-inspired electronic music with organic textures',
    prompts: [
      { color: '#2ecc71', text: 'Nature Samples' },
      { color: '#27ae60', text: 'Organic Percussion' },
      { color: '#1abc9c', text: 'Ambient Pads' },
      { color: '#16a085', text: 'Forest Soundscape' },
      { color: '#3498db', text: 'Flowing Synth' },
      { color: '#2980b9', text: 'Wind Chimes' },
      { color: '#8e44ad', text: 'Earthy Bass' },
      { color: '#9b59b6', text: 'Bird Calls' },
      { color: '#f39c12', text: 'Water Droplets' },
      { color: '#e67e22', text: 'Wooden Percussion' },
      { color: '#d35400', text: 'Leaf Rustle' },
      { color: '#c0392b', text: 'Natural Reverb' },
      { color: '#7f8c8d', text: 'Ethereal Vocal' },
      { color: '#95a5a6', text: 'Bamboo Flute' },
      { color: '#34495e', text: 'Zen Melody' },
      { color: '#2c3e50', text: 'Peaceful Harmony' },
    ],
  },
  'hyperpop-fusion': {
    name: 'Hyperpop Fusion',
    description: 'Maximalist production, distorted vocals, chaotic energy',
    prompts: [
      { color: '#ff0080', text: 'Distorted Vocals' },
      { color: '#00ffff', text: 'Hyper Bass' },
      { color: '#ff00ff', text: 'Glitchy Drums' },
      { color: '#ffff00', text: 'Pitched Vocals' },
      { color: '#00ff00', text: 'Chaotic Synth' },
      { color: '#ff0000', text: 'Heavy Sidechain' },
      { color: '#0000ff', text: 'Auto-Tune Effect' },
      { color: '#ff8800', text: 'Maxed Out 808' },
      { color: '#8800ff', text: 'Digital Distortion' },
      { color: '#00ff88', text: 'Rapid Fire Fills' },
      { color: '#ff0088', text: 'Vocal Chops' },
      { color: '#88ff00', text: 'Glitch Effects' },
      { color: '#0088ff', text: 'Loud Synth Lead' },
      { color: '#ff8800', text: 'Compressed Drums' },
      { color: '#8800ff', text: 'Maximalist Pads' },
      { color: '#00ff88', text: 'Clipped Bass' },
    ],
  },
  'global-bass': {
    name: 'Global Bass',
    description: 'World music influences with bass-heavy electronic production',
    prompts: [
      { color: '#e74c3c', text: 'Ethnic Percussion' },
      { color: '#e67e22', text: 'Dubstep Wobble' },
      { color: '#f39c12', text: 'World Instruments' },
      { color: '#f1c40f', text: 'Heavy Sub Bass' },
      { color: '#16a085', text: 'African Drums' },
      { color: '#27ae60', text: 'Asian Strings' },
      { color: '#2980b9', text: 'Latin Rhythm' },
      { color: '#8e44ad', text: 'Bass Drop' },
      { color: '#2c3e50', text: 'Middle Eastern Scale' },
      { color: '#c0392b', text: 'Global Vocal Sample' },
      { color: '#d35400', text: 'Tabla Beats' },
      { color: '#7f8c8d', text: 'Sitar Melody' },
      { color: '#bdc3c7', text: 'Caribbean Vibe' },
      { color: '#95a5a6', text: 'Balkan Brass' },
      { color: '#34495e', text: 'Electronic Fusion' },
      { color: '#1abc9c', text: 'Cultural Bass' },
    ],
  },
  'psychedelic-rnb': {
    name: 'Psychedelic R&B',
    description: 'Trippy effects, soulful vocals, experimental production',
    prompts: [
      { color: '#9b59b6', text: 'Phaser Vocals' },
      { color: '#8e44ad', text: 'Soulful Keys' },
      { color: '#3498db', text: 'Trippy Pads' },
      { color: '#2980b9', text: 'Delayed Guitar' },
      { color: '#1abc9c', text: 'Groovy Bass' },
      { color: '#16a085', text: 'Reverb Drums' },
      { color: '#27ae60', text: 'Spacey Synth' },
      { color: '#2ecc71', text: 'Vocal Harmonies' },
      { color: '#f39c12', text: 'Wah Guitar' },
      { color: '#e67e22', text: 'Experimental Beat' },
      { color: '#e74c3c', text: 'Filtered Rhodes' },
      { color: '#c0392b', text: 'Flanger Effect' },
      { color: '#ecf0f1', text: 'Dreamy Texture' },
      { color: '#bdc3c7', text: 'Psychedelic Lead' },
      { color: '#95a5a6', text: 'Chorus Strings' },
      { color: '#7f8c8d', text: 'Ambient Soul' },
    ],
  },
  'post-genre-fusion': {
    name: 'Post-Genre Fusion',
    description: 'Experimental blend of multiple genres and styles',
    prompts: [
      { color: '#e056fd', text: 'Genre-Bending Lead' },
      { color: '#686de0', text: 'Fusion Bass' },
      { color: '#4834df', text: 'Experimental Drums' },
      { color: '#30336b', text: 'Abstract Melody' },
      { color: '#f9ca24', text: 'Hybrid Percussion' },
      { color: '#f0932b', text: 'Cross-Genre Chords' },
      { color: '#eb4d4b', text: 'Eclectic Vocal' },
      { color: '#6ab04c', text: 'Unconventional Rhythm' },
      { color: '#22a6b3', text: 'Diverse Textures' },
      { color: '#be2edd', text: 'Fusion Synth' },
      { color: '#4834d4', text: 'Mixed Elements' },
      { color: '#f9ca24', text: 'Genre Mashup' },
      { color: '#eb3b5a', text: 'Experimental Keys' },
      { color: '#20bf6b', text: 'Avant-Garde Beat' },
      { color: '#0fb9b1', text: 'Future Sound' },
      { color: '#a55eea', text: 'Boundary-Breaking' },
    ],
  },
};

export const ALL_PRESETS = { ...REGIONAL_PRESETS, ...MODERN_PRESETS };
